#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

#TO DO - Add check for root user 

trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 9 15
echo "$BASHPID" > /run/$(basename $0).pid

unset -v RootPart
unset -v GrubMenu
unset -v PartDrive
unset -v PartDriveSize
unset -v PartDriveMenu

Drives=$(cat /proc/partitions | grep -v loop | grep -v "^$" | grep -v sr | grep -v name | grep -v zram | awk '{ print $4}')
Question='yad --timeout=10 --text-align=fill --borders=6 --skip-taskbar --sticky --wrap --center --image=gtk-dialog-question --button=gtk-no:1 --button=Si:0 --title="Chdir"'


# posibilidad de levantar varios chroot de manera simultaneas
# English Translation - possibility of raising several chroot simultaneously

# preguntar si desea limpiar los chroot
# English Translation - ask if you want to clean the chroot

chdir="/tmp/chdir"

pre_ch (){
	mkdir -p $chdir
	mkdir -p $chdir/proc
	mkdir -p $chdir/dev
	mkdir -p $chdir/sys
	mount -o bind /proc $chdir/proc
	mount -o bind /dev  $chdir/dev
	mount -o bind /sys  $chdir/sys
}

post_ch (){
	for j in $(mount | grep "$chdir" | awk '{print $3}'); do
		umount -fl "$j"
	done
}

for i in $Drives; do
	PartDrive="$i"
	PartDriveSize=$(grep -m 1 "$i" /proc/partitions | awk '{print $3}')
	if [ "$(echo "$PartDrive" | grep [0-9] )" != "" ]; then
		if [ "$PartDriveMenu" = "" ]; then
			PartDriveMenu=("$PartDrive")
		else
			PartDriveMenu=("${PartDriveMenu[@]}" "$PartDrive")
		fi
	fi
done

GetRootPart (){
	RootPart=$(yad --text-align=fill --borders=6 --sticky --no-click --center --height="300" --list --title="Chroot Selection" --column="Name" --button="Exit":3 --button=$"gtk-ok:2" --text="Select the system root partition." "${PartDriveMenu[@]}")
	ret="$?"

	if [ "$ret" = "3" ]; then
		$Question --text="Are you sure you want to cancel?"
	  	if [[ $? = 0 ]]; then
	   		exit 1
		else
	   		GetRootPart
		fi
	elif [ "$ret" = "252" ]; then
		GetRootPart
	elif [ "$RootPart" = "" ]; then
		$Info --text="You didn't select a partition, Please select a partition." --button=$"gtk-ok:1"
		GetRootPart
	fi
	RootPart=$(echo "$RootPart" | awk -F '|' '{print $1}')
}

post_ch

GetRootPart

pre_ch
mount -o rw /dev/"$RootPart" "$chdir"

#x-terminal-emulator -e "chroot $chdir"

post_ch

echo "Finshed"
exit 0
